Vagrant.configure("2") do |config|
  config.vm.box = "punktde/freebsd-132-ufs"

  config.vm.network 'private_network', ip: '192.168.56.23'

  # share the project directory with the guest
  #
  config.vm.synced_folder '.', '/var/vagrant', :nfs => true, :nfs_version => 3
end
