Vagrant.configure("2") do |config|
  config.vm.box = "punktde/freebsd-132-ufs"

  # Method #1 - set up an explicit port forward
  #
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Method #2 - use a host-only network
  #
  config.vm.network 'private_network', ip: '192.168.56.23'

  config.vm.provision 'shell', inline: <<-SHELL
    export ASSUME_ALWAYS_YES=yes
    pkg install apache24
    sysrc apache24_enable=YES
    service apache24 start
  SHELL
end
