Vagrant.configure(2) do |config|

  # configuration common to all VMs goes here
  #
  config.vm.box = "punktde/freebsd-132-ufs"
  config.vm.synced_folder '.', '/vagrant', id: 'vagrant-root', disabled: true
  config.vm.synced_folder '.', '/var/vagrant', :nfs => true, :nfs_version => 3

  # bring those memory and CPU requirements down a bit
  #
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # provision a common hosts file to all VMs
  #
  config.vm.provision 'shell', inline: <<-SHELL
    # get rid of Linuxism inserted by Vagrant
    sed -i '' '/127\.0\.1\.1/d' /etc/hosts

    # add the IP addresses of the three nodes
    grep -q node1 /etc/hosts || echo "192.168.56.51 node1" >>/etc/hosts
    grep -q node2 /etc/hosts || echo "192.168.56.52 node2" >>/etc/hosts
    grep -q node3 /etc/hosts || echo "192.168.56.53 node3" >>/etc/hosts
  SHELL

  # configuration for individual VMs
  #
  config.vm.define "node1" do |node1|
    node1.vm.hostname = 'node1'
    node1.vm.network 'private_network', ip: '192.168.56.51'
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = 'node2'
    node2.vm.network 'private_network', ip: '192.168.56.52'
  end

  config.vm.define "node3" do |node3|
    node3.vm.hostname = 'node3'
    node3.vm.network 'private_network', ip: '192.168.56.53'
  end

end
